# Generated by Django 3.2.4 on 2021-06-10 16:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Admin', 'ADMIN'), ('Staff', 'STAFF')], default=[], max_length=11, null=True),
        ),
    ]
