# Generated by Django 3.2.4 on 2021-06-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('login.user',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('login.user',),
        ),
    ]
