# Generated by Django 3.2.4 on 2021-06-18 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_admin_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=60)),
                ('minrank', models.IntegerField()),
                ('maxrank', models.IntegerField()),
                ('url', models.CharField(max_length=600)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
