# Generated by Django 3.2.4 on 2021-06-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_clinical_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinical',
            name='owner',
        ),
        migrations.AddField(
            model_name='clinical',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
